package com.comtrade.domain;

public enum ConstantBl {
	POST, GET_ALL, PUT, DELETE, POST_LOGIN, GET_ALL_R, GET_ALL_U, GET_ONE, GET_R_CAT, POST_R_CU,
	DELETE_R_CU, POST_R_CA, DELETE_R_CA, POST_R_MEAL, DELETE_R_MEAL, GET_R_CU, GET_MEALS_4_CAT, GET_R_MEAL,
	GET_ONE_R_NAME, POST_USER, PUT_PASS

}
